/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ooada1;

/**
 *
 * @author Muhammad Fakhar
 */
public class BorrowerLoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form BorrowerLogin
     */
    private Person typeOfPerson;
    private Library LMS;
    public BorrowerLoginGUI(Person type, Library lib)
    {
        this.typeOfPerson = type;
        this.LMS = lib;
        initComponents();
    }
    public BorrowerLoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        borrowerReserveBookBtn = new javax.swing.JButton();
        borrowerPersonalInfoBtn = new javax.swing.JButton();
        borrowerSearchBooksBtn = new javax.swing.JButton();
        borrowerLogOutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borrower", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(java.awt.Color.black);

        borrowerReserveBookBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        borrowerReserveBookBtn.setForeground(java.awt.Color.black);
        borrowerReserveBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/hold.png"))); // NOI18N
        borrowerReserveBookBtn.setText("Reserve a Book ");
        borrowerReserveBookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowerReserveBookBtnMouseClicked(evt);
            }
        });

        borrowerPersonalInfoBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        borrowerPersonalInfoBtn.setForeground(java.awt.Color.black);
        borrowerPersonalInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/personalinfo.png"))); // NOI18N
        borrowerPersonalInfoBtn.setText("View Personal Info");
        borrowerPersonalInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowerPersonalInfoBtnMouseClicked(evt);
            }
        });

        borrowerSearchBooksBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        borrowerSearchBooksBtn.setForeground(java.awt.Color.black);
        borrowerSearchBooksBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/search.png"))); // NOI18N
        borrowerSearchBooksBtn.setText("Search Books");
        borrowerSearchBooksBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowerSearchBooksBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(borrowerReserveBookBtn)
                    .addComponent(borrowerSearchBooksBtn)
                    .addComponent(borrowerPersonalInfoBtn))
                .addGap(184, 184, 184))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(borrowerPersonalInfoBtn)
                .addGap(29, 29, 29)
                .addComponent(borrowerSearchBooksBtn)
                .addGap(28, 28, 28)
                .addComponent(borrowerReserveBookBtn)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        borrowerLogOutBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        borrowerLogOutBtn.setForeground(java.awt.Color.black);
        borrowerLogOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/logout.png"))); // NOI18N
        borrowerLogOutBtn.setText("LogOut");
        borrowerLogOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowerLogOutBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(borrowerLogOutBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(borrowerLogOutBtn)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrowerLogOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowerLogOutBtnMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new LoginGUI(LMS).setVisible(true);
            }
        });
    }//GEN-LAST:event_borrowerLogOutBtnMouseClicked

    private void borrowerPersonalInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowerPersonalInfoBtnMouseClicked
        // TODO add your handling code here:
        PersonalInfoGUI pInfo = new PersonalInfoGUI(typeOfPerson, LMS);
        this.setVisible(false);
        pInfo.setVisible(true);

    }//GEN-LAST:event_borrowerPersonalInfoBtnMouseClicked

    private void borrowerSearchBooksBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowerSearchBooksBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBooksGUI(typeOfPerson, LMS).setVisible(true);
            }
        });
         
    }//GEN-LAST:event_borrowerSearchBooksBtnMouseClicked

    private void borrowerReserveBookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowerReserveBookBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReserveBookGUI(typeOfPerson, LMS).setVisible(true);
            }
        });
    }//GEN-LAST:event_borrowerReserveBookBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowerLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowerLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowerLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowerLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrowerLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrowerLogOutBtn;
    private javax.swing.JButton borrowerPersonalInfoBtn;
    private javax.swing.JButton borrowerReserveBookBtn;
    private javax.swing.JButton borrowerSearchBooksBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
