/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ooada1;

/**
 *
 * @author Muhammad Fakhar
 */
public class ClerkLoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClerkLogin
     */
    private Person typeOfPerson;
    private Library LMS;
    public ClerkLoginGUI(Person type, Library lib)
    {
        initComponents();
        this.LMS = lib;
        this.typeOfPerson = type;
    }
    public ClerkLoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        clerkReserveBookBtn = new javax.swing.JButton();
        clerkPersonalInfoBtn = new javax.swing.JButton();
        clerkSearchBooksBtn = new javax.swing.JButton();
        clerkCheckOutBtn = new javax.swing.JButton();
        clerkCheckInBtn = new javax.swing.JButton();
        clerkRenewBtn = new javax.swing.JButton();
        clerkAddBorrowerBtn = new javax.swing.JButton();
        clerkUpdateBorrowerBtn = new javax.swing.JButton();
        clerkLogOutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clerk", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        clerkReserveBookBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clerkReserveBookBtn.setForeground(new java.awt.Color(0, 0, 0));
        clerkReserveBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/hold.png"))); // NOI18N
        clerkReserveBookBtn.setText("Reserve a Book ");
        clerkReserveBookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clerkReserveBookBtnMouseClicked(evt);
            }
        });
        clerkReserveBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clerkReserveBookBtnActionPerformed(evt);
            }
        });

        clerkPersonalInfoBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clerkPersonalInfoBtn.setForeground(new java.awt.Color(0, 0, 0));
        clerkPersonalInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/personalinfo.png"))); // NOI18N
        clerkPersonalInfoBtn.setText("View Personal Info");
        clerkPersonalInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clerkPersonalInfoBtnMouseClicked(evt);
            }
        });

        clerkSearchBooksBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clerkSearchBooksBtn.setForeground(new java.awt.Color(0, 0, 0));
        clerkSearchBooksBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/search.png"))); // NOI18N
        clerkSearchBooksBtn.setText("Search Books");
        clerkSearchBooksBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clerkSearchBooksBtnMouseClicked(evt);
            }
        });

        clerkCheckOutBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clerkCheckOutBtn.setForeground(new java.awt.Color(0, 0, 0));
        clerkCheckOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/book.png"))); // NOI18N
        clerkCheckOutBtn.setText("Check Out a Book");
        clerkCheckOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clerkCheckOutBtnMouseClicked(evt);
            }
        });

        clerkCheckInBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clerkCheckInBtn.setForeground(new java.awt.Color(0, 0, 0));
        clerkCheckInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/checkin.png"))); // NOI18N
        clerkCheckInBtn.setText("Check In a Book");
        clerkCheckInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clerkCheckInBtnMouseClicked(evt);
            }
        });
        clerkCheckInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clerkCheckInBtnActionPerformed(evt);
            }
        });

        clerkRenewBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clerkRenewBtn.setForeground(new java.awt.Color(0, 0, 0));
        clerkRenewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/renew.png"))); // NOI18N
        clerkRenewBtn.setText("Renew a Book");
        clerkRenewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clerkRenewBtnMouseClicked(evt);
            }
        });

        clerkAddBorrowerBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clerkAddBorrowerBtn.setForeground(new java.awt.Color(0, 0, 0));
        clerkAddBorrowerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/addperson.png"))); // NOI18N
        clerkAddBorrowerBtn.setText("Add a Borrower");
        clerkAddBorrowerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clerkAddBorrowerBtnMouseClicked(evt);
            }
        });

        clerkUpdateBorrowerBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clerkUpdateBorrowerBtn.setForeground(new java.awt.Color(0, 0, 0));
        clerkUpdateBorrowerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/update.png"))); // NOI18N
        clerkUpdateBorrowerBtn.setText("Update Borrower's Information");
        clerkUpdateBorrowerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clerkUpdateBorrowerBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clerkReserveBookBtn)
                    .addComponent(clerkSearchBooksBtn)
                    .addComponent(clerkPersonalInfoBtn)
                    .addComponent(clerkCheckOutBtn)
                    .addComponent(clerkCheckInBtn)
                    .addComponent(clerkRenewBtn)
                    .addComponent(clerkAddBorrowerBtn)
                    .addComponent(clerkUpdateBorrowerBtn))
                .addGap(184, 184, 184))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clerkPersonalInfoBtn)
                .addGap(18, 18, 18)
                .addComponent(clerkSearchBooksBtn)
                .addGap(18, 18, 18)
                .addComponent(clerkReserveBookBtn)
                .addGap(18, 18, 18)
                .addComponent(clerkCheckOutBtn)
                .addGap(18, 18, 18)
                .addComponent(clerkCheckInBtn)
                .addGap(18, 18, 18)
                .addComponent(clerkRenewBtn)
                .addGap(18, 18, 18)
                .addComponent(clerkAddBorrowerBtn)
                .addGap(18, 18, 18)
                .addComponent(clerkUpdateBorrowerBtn)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        clerkLogOutBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clerkLogOutBtn.setForeground(new java.awt.Color(0, 0, 0));
        clerkLogOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/logout.png"))); // NOI18N
        clerkLogOutBtn.setText("Log Out");
        clerkLogOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clerkLogOutBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clerkLogOutBtn)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(clerkLogOutBtn)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clerkCheckInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clerkCheckInBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clerkCheckInBtnActionPerformed

    private void clerkPersonalInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clerkPersonalInfoBtnMouseClicked
          PersonalInfoGUI pInfo = new PersonalInfoGUI(typeOfPerson, LMS);
          this.setVisible(false);
          pInfo.setVisible(true);
    }//GEN-LAST:event_clerkPersonalInfoBtnMouseClicked

    private void clerkSearchBooksBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clerkSearchBooksBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new SearchBooksGUI(typeOfPerson, LMS).setVisible(true);
            }
        });
    }//GEN-LAST:event_clerkSearchBooksBtnMouseClicked

    private void clerkReserveBookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clerkReserveBookBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new ReserveBookGUI(typeOfPerson, LMS).setVisible(true);
            }
        });
    }//GEN-LAST:event_clerkReserveBookBtnMouseClicked

    private void clerkCheckOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clerkCheckOutBtnMouseClicked
        // TODO add your handling code here:
        CheckOutGUI checkOut = new CheckOutGUI(typeOfPerson, LMS);
        checkOut.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_clerkCheckOutBtnMouseClicked

    private void clerkLogOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clerkLogOutBtnMouseClicked
        // TODO add your handling code here:
          this.setVisible(false);
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new LoginGUI(LMS).setVisible(true);
            }
        });
    }//GEN-LAST:event_clerkLogOutBtnMouseClicked

    private void clerkCheckInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clerkCheckInBtnMouseClicked
        // TODO add your handling code here:
        CheckInBookGUI checkIn = new CheckInBookGUI(typeOfPerson, LMS);
        checkIn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_clerkCheckInBtnMouseClicked

    private void clerkRenewBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clerkRenewBtnMouseClicked
        // TODO add your handling code here:
        RenewBookGUI renew = new RenewBookGUI(typeOfPerson, LMS);
        renew.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_clerkRenewBtnMouseClicked

    private void clerkAddBorrowerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clerkAddBorrowerBtnMouseClicked
        // TODO add your handling code here:
        AddBorrowerGUI addBor = new AddBorrowerGUI(typeOfPerson, LMS);
        addBor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_clerkAddBorrowerBtnMouseClicked

    private void clerkUpdateBorrowerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clerkUpdateBorrowerBtnMouseClicked
        // TODO add your handling code here:
        EditBorrowerInfoGUI editBor = new EditBorrowerInfoGUI(typeOfPerson, LMS);
        editBor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_clerkUpdateBorrowerBtnMouseClicked

    private void clerkReserveBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clerkReserveBookBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clerkReserveBookBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClerkLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClerkLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClerkLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClerkLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClerkLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clerkAddBorrowerBtn;
    private javax.swing.JButton clerkCheckInBtn;
    private javax.swing.JButton clerkCheckOutBtn;
    private javax.swing.JButton clerkLogOutBtn;
    private javax.swing.JButton clerkPersonalInfoBtn;
    private javax.swing.JButton clerkRenewBtn;
    private javax.swing.JButton clerkReserveBookBtn;
    private javax.swing.JButton clerkSearchBooksBtn;
    private javax.swing.JButton clerkUpdateBorrowerBtn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
