/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ooada1;

/**
 *
 * @author Muhammad Fakhar
 */
public class LibrarianLoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianLogin
     */
    Person typeOfPerson;
    private Library LMS;
    public LibrarianLoginGUI(Person type, Library lib)
    {
        initComponents();
        this.LMS = lib;
        this.typeOfPerson = type;
    }
    public LibrarianLoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        librarianReserveBookBtn = new javax.swing.JButton();
        librarianPersonalInfoBtn = new javax.swing.JButton();
        librarianSearchBooksBtn = new javax.swing.JButton();
        librarianCheckOutBtn = new javax.swing.JButton();
        librarianCheckInBtn = new javax.swing.JButton();
        librarianRenewBtn = new javax.swing.JButton();
        librarianAddBorrowerBtn = new javax.swing.JButton();
        librarianUpdateBorrowerBtn = new javax.swing.JButton();
        librarianAddBookBtn = new javax.swing.JButton();
        librarianRemoveBookBtn = new javax.swing.JButton();
        librarianUpdateBookBtn = new javax.swing.JButton();
        librarianLogOutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Librarian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(java.awt.Color.black);

        librarianReserveBookBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        librarianReserveBookBtn.setForeground(java.awt.Color.black);
        librarianReserveBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/hold.png"))); // NOI18N
        librarianReserveBookBtn.setText("Reserve a Book ");
        librarianReserveBookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarianReserveBookBtnMouseClicked(evt);
            }
        });

        librarianPersonalInfoBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        librarianPersonalInfoBtn.setForeground(java.awt.Color.black);
        librarianPersonalInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/personalinfo.png"))); // NOI18N
        librarianPersonalInfoBtn.setText("View Personal Info");
        librarianPersonalInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarianPersonalInfoBtnMouseClicked(evt);
            }
        });

        librarianSearchBooksBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        librarianSearchBooksBtn.setForeground(java.awt.Color.black);
        librarianSearchBooksBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/search.png"))); // NOI18N
        librarianSearchBooksBtn.setText("Search Books");
        librarianSearchBooksBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarianSearchBooksBtnMouseClicked(evt);
            }
        });

        librarianCheckOutBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        librarianCheckOutBtn.setForeground(java.awt.Color.black);
        librarianCheckOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/book.png"))); // NOI18N
        librarianCheckOutBtn.setText("Check Out a Book");
        librarianCheckOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarianCheckOutBtnMouseClicked(evt);
            }
        });

        librarianCheckInBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        librarianCheckInBtn.setForeground(java.awt.Color.black);
        librarianCheckInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/checkin.png"))); // NOI18N
        librarianCheckInBtn.setText("Check In a Book");
        librarianCheckInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarianCheckInBtnMouseClicked(evt);
            }
        });
        librarianCheckInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianCheckInBtnActionPerformed(evt);
            }
        });

        librarianRenewBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        librarianRenewBtn.setForeground(java.awt.Color.black);
        librarianRenewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/renew.png"))); // NOI18N
        librarianRenewBtn.setText("Renew a Book");
        librarianRenewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarianRenewBtnMouseClicked(evt);
            }
        });

        librarianAddBorrowerBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        librarianAddBorrowerBtn.setForeground(java.awt.Color.black);
        librarianAddBorrowerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/addperson.png"))); // NOI18N
        librarianAddBorrowerBtn.setText("Add a Borrower");
        librarianAddBorrowerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarianAddBorrowerBtnMouseClicked(evt);
            }
        });
        librarianAddBorrowerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                librarianAddBorrowerBtnActionPerformed(evt);
            }
        });

        librarianUpdateBorrowerBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        librarianUpdateBorrowerBtn.setForeground(java.awt.Color.black);
        librarianUpdateBorrowerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/update.png"))); // NOI18N
        librarianUpdateBorrowerBtn.setText("Update Borrower's Information");
        librarianUpdateBorrowerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarianUpdateBorrowerBtnMouseClicked(evt);
            }
        });

        librarianAddBookBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        librarianAddBookBtn.setForeground(java.awt.Color.black);
        librarianAddBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/addbook.png"))); // NOI18N
        librarianAddBookBtn.setText("Add a Book");
        librarianAddBookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarianAddBookBtnMouseClicked(evt);
            }
        });

        librarianRemoveBookBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        librarianRemoveBookBtn.setForeground(java.awt.Color.black);
        librarianRemoveBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/rembook.png"))); // NOI18N
        librarianRemoveBookBtn.setText("Remove a Book");
        librarianRemoveBookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarianRemoveBookBtnMouseClicked(evt);
            }
        });

        librarianUpdateBookBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        librarianUpdateBookBtn.setForeground(java.awt.Color.black);
        librarianUpdateBookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/update.png"))); // NOI18N
        librarianUpdateBookBtn.setText("Update a Book's Information");
        librarianUpdateBookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarianUpdateBookBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(librarianReserveBookBtn)
                    .addComponent(librarianSearchBooksBtn)
                    .addComponent(librarianPersonalInfoBtn)
                    .addComponent(librarianCheckOutBtn)
                    .addComponent(librarianCheckInBtn)
                    .addComponent(librarianRenewBtn)
                    .addComponent(librarianAddBorrowerBtn)
                    .addComponent(librarianUpdateBorrowerBtn)
                    .addComponent(librarianAddBookBtn)
                    .addComponent(librarianRemoveBookBtn)
                    .addComponent(librarianUpdateBookBtn))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(librarianPersonalInfoBtn)
                .addGap(18, 18, 18)
                .addComponent(librarianSearchBooksBtn)
                .addGap(18, 18, 18)
                .addComponent(librarianReserveBookBtn)
                .addGap(18, 18, 18)
                .addComponent(librarianCheckOutBtn)
                .addGap(18, 18, 18)
                .addComponent(librarianCheckInBtn)
                .addGap(18, 18, 18)
                .addComponent(librarianRenewBtn)
                .addGap(18, 18, 18)
                .addComponent(librarianAddBorrowerBtn)
                .addGap(18, 18, 18)
                .addComponent(librarianUpdateBorrowerBtn)
                .addGap(18, 18, 18)
                .addComponent(librarianAddBookBtn)
                .addGap(18, 18, 18)
                .addComponent(librarianRemoveBookBtn)
                .addGap(18, 18, 18)
                .addComponent(librarianUpdateBookBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        librarianLogOutBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        librarianLogOutBtn.setForeground(new java.awt.Color(0, 0, 0));
        librarianLogOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooada1/logout.png"))); // NOI18N
        librarianLogOutBtn.setText("Log Out");
        librarianLogOutBtn.setToolTipText("");
        librarianLogOutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                librarianLogOutBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(414, Short.MAX_VALUE)
                .addComponent(librarianLogOutBtn)
                .addGap(17, 17, 17))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(librarianLogOutBtn)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void librarianCheckInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianCheckInBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_librarianCheckInBtnActionPerformed

    private void librarianPersonalInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarianPersonalInfoBtnMouseClicked
        // TODO add your handling code here:
         PersonalInfoGUI pInfo = new PersonalInfoGUI(typeOfPerson, LMS);
          this.setVisible(false);
          pInfo.setVisible(true);
    }//GEN-LAST:event_librarianPersonalInfoBtnMouseClicked

    private void librarianLogOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarianLogOutBtnMouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() 
            {
                new LoginGUI(LMS).setVisible(true);
            }
        });
    }//GEN-LAST:event_librarianLogOutBtnMouseClicked

    private void librarianSearchBooksBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarianSearchBooksBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBooksGUI(typeOfPerson, LMS).setVisible(true);
            }
        });
    }//GEN-LAST:event_librarianSearchBooksBtnMouseClicked

    private void librarianReserveBookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarianReserveBookBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReserveBookGUI(typeOfPerson, LMS).setVisible(true);
            }
        });
    }//GEN-LAST:event_librarianReserveBookBtnMouseClicked

    private void librarianCheckOutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarianCheckOutBtnMouseClicked
        // TODO add your handling code here:
         CheckOutGUI checkOut = new CheckOutGUI(typeOfPerson, LMS);
        checkOut.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_librarianCheckOutBtnMouseClicked

    private void librarianCheckInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarianCheckInBtnMouseClicked
        // TODO add your handling code here:
        CheckInBookGUI checkIn = new CheckInBookGUI(typeOfPerson, LMS);
        checkIn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_librarianCheckInBtnMouseClicked

    private void librarianRenewBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarianRenewBtnMouseClicked
        // TODO add your handling code here:
        RenewBookGUI renew = new RenewBookGUI(typeOfPerson, LMS);
        renew.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_librarianRenewBtnMouseClicked

    private void librarianAddBorrowerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarianAddBorrowerBtnMouseClicked
        // TODO add your handling code here:
        AddBorrowerGUI addBor = new AddBorrowerGUI(typeOfPerson, LMS);
        addBor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_librarianAddBorrowerBtnMouseClicked

    private void librarianUpdateBorrowerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarianUpdateBorrowerBtnMouseClicked
        // TODO add your handling code here:
        EditBorrowerInfoGUI editBor = new EditBorrowerInfoGUI(typeOfPerson, LMS);
        editBor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_librarianUpdateBorrowerBtnMouseClicked

    private void librarianAddBookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarianAddBookBtnMouseClicked
        // TODO add your handling code here:
        AddBookGUI addBook = new AddBookGUI(typeOfPerson, LMS);
        addBook.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_librarianAddBookBtnMouseClicked

    private void librarianRemoveBookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarianRemoveBookBtnMouseClicked
        // TODO add your handling code here:
        DeleteBookGUI delBook = new DeleteBookGUI(typeOfPerson, LMS);
        delBook.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_librarianRemoveBookBtnMouseClicked

    private void librarianUpdateBookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_librarianUpdateBookBtnMouseClicked
        // TODO add your handling code here:
        EditBookInfoGUI editBook = new EditBookInfoGUI(typeOfPerson, LMS);
        editBook.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_librarianUpdateBookBtnMouseClicked

    private void librarianAddBorrowerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_librarianAddBorrowerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_librarianAddBorrowerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton librarianAddBookBtn;
    private javax.swing.JButton librarianAddBorrowerBtn;
    private javax.swing.JButton librarianCheckInBtn;
    private javax.swing.JButton librarianCheckOutBtn;
    private javax.swing.JButton librarianLogOutBtn;
    private javax.swing.JButton librarianPersonalInfoBtn;
    private javax.swing.JButton librarianRemoveBookBtn;
    private javax.swing.JButton librarianRenewBtn;
    private javax.swing.JButton librarianReserveBookBtn;
    private javax.swing.JButton librarianSearchBooksBtn;
    private javax.swing.JButton librarianUpdateBookBtn;
    private javax.swing.JButton librarianUpdateBorrowerBtn;
    // End of variables declaration//GEN-END:variables
}
